In [1]:
import numpy as np

In [2]:
a = [[1,2,3],
     [4,5,6],
     [7,8,8]]

In [3]:
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 8]]


In [4]:
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [5]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 8]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [15]:
c = np.array([[3,5,6],
             [9,10,11],
             [7,6,4]])
print(c)





[[ 3  5  6]
 [ 9 10 11]
 [ 7  6  4]]


In [17]:
e = b.dot(c)
print(e)

[[ 42  43  40]
 [ 99 106 103]
 [149 163 162]]


In [18]:
b @ c







array([[ 42,  43,  40],
       [ 99, 106, 103],
       [149, 163, 162]])

In [19]:
f = np.where(b < 43, e, e*10)

In [20]:
f

array([[ 42,  43,  40],
       [ 99, 106, 103],
       [149, 163, 162]])